# Generated by Django 5.0.4 on 2024-04-26 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key='True', serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantPersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name on national ID', max_length=100, verbose_name='Your first name')),
                ('last_name', models.CharField(help_text='Last name on national ID', max_length=100, verbose_name='Your last name')),
                ('bio', models.TextField(help_text='Tell us about yourself in a few words', verbose_name='Tell us about yourself')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Your phone number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Your Address')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='apply.userapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(help_text=' Year you started your extracurricular activity', verbose_name='What Year did you start your extracurricular activity')),
                ('end_year', models.IntegerField(help_text=' Year you finished your extracurricular activity', verbose_name='What Year Did You Finish Your extracurricular activity')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracurricular_activity', to='apply.userapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, help_text='Your CV in PDF format', null=True, upload_to='documents/')),
                ('transcript', models.FileField(blank=True, help_text='Your transcript in PDF format', null=True, upload_to='documents/')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apply.userapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantAcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='It can be anything like university or others', max_length=200, verbose_name='Institution name you attended')),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Associate', 'Associate'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Other', 'Other')], help_text='Degrees your are qualified with like diplomas or others', max_length=100, verbose_name='Your Degrees')),
                ('field_of_study', models.CharField(help_text='It can be like computer science or others', max_length=100, verbose_name='What is your field of study ?')),
                ('graduation_year', models.DateField(help_text=' Year you graduated from your institution', verbose_name='What year did you graduate')),
                ('start_year', models.IntegerField(help_text=' Year you started your institution', verbose_name='When did you start your institution year ?')),
                ('end_year', models.IntegerField(help_text=' Year you finished your institution', verbose_name='When Did You Finish Your Institution Year ?')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_background', to='apply.userapplication')),
            ],
        ),
    ]
