# Generated by Django 5.0.4 on 2024-04-27 11:28

from django.db import migrations
from django.contrib.auth.models import Permission, Group
from django.contrib.auth import get_user_model as User
from django.contrib.contenttypes.models import ContentType
from apply.models import (
    UserApplication,
    ApplicantDocument,
    ApplicantAcademicBackground,
    ApplicantExtracurricularActivity,
    ApplicantPersonalInformation,
)


def create_permissions_and_groups(app, schema_editor):
    # Create Groups
    applicant_group, created = Group.objects.get_or_create(name="Applicant")
    manager_group, created = Group.objects.get_or_create(name="Manager")

    # Define Permissions
    can_add_user_application = Permission.objects.create(
        codename="add_user_application",
        name="Can add user application",
        content_type=ContentType.objects.get_for_model(UserApplication),
    )
    can_delete_user_application = Permission.objects.create(
        codename="delete_user_application",
        name="Can delete user application",
        content_type=ContentType.objects.get_for_model(UserApplication),
    )

    can_change_user_application = Permission.objects.create(
        codename="change_user_application",
        name="Can change user application",
        content_type=ContentType.objects.get_for_model(UserApplication),
    )

    applicant_group.permissions.add(
        can_add_user_application, can_change_user_application
    )
    manager_group.permissions.add(can_delete_user_application)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_permissions_and_groups),
    ]
