# Generated by Django 5.0.4 on 2024-04-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_create_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_manager',
        ),
    ]
